import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Link } from 'react-router-dom';
import { ShoppingCart, Eye } from 'lucide-react';
import { useCartStore } from '../store/cartStore';
import { motion } from 'motion/react';
export default function ProductCard({ product }) {
    const { addItem } = useCartStore();
    return (_jsxs(motion.div, { initial: { opacity: 0, y: 20 }, whileInView: { opacity: 1, y: 0 }, viewport: { once: true }, className: "card group", children: [_jsxs("div", { className: "relative aspect-[4/5] overflow-hidden", children: [_jsx("img", { src: product.image_url, alt: product.name, className: "w-full h-full object-cover transition-transform duration-500 group-hover:scale-110", referrerPolicy: "no-referrer" }), _jsxs("div", { className: "absolute inset-0 bg-black/20 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center space-x-4", children: [_jsx(Link, { to: `/product/${product.id}`, className: "w-12 h-12 bg-white rounded-full flex items-center justify-center text-primary-green hover:bg-primary-green hover:text-white transition-all shadow-lg", children: _jsx(Eye, { className: "w-6 h-6" }) }), _jsx("button", { onClick: () => addItem(product), className: "w-12 h-12 bg-accent-orange rounded-full flex items-center justify-center text-white hover:scale-110 transition-all shadow-lg", children: _jsx(ShoppingCart, { className: "w-6 h-6" }) })] }), product.stock < 5 && product.stock > 0 && (_jsx("span", { className: "absolute top-4 left-4 bg-accent-orange text-white text-[10px] font-bold px-2 py-1 rounded-full uppercase tracking-wider", children: "Low Stock" })), product.stock === 0 && (_jsx("span", { className: "absolute top-4 left-4 bg-zinc-500 text-white text-[10px] font-bold px-2 py-1 rounded-full uppercase tracking-wider", children: "Out of Stock" }))] }), _jsxs("div", { className: "p-4 space-y-1", children: [_jsxs("div", { className: "flex justify-between items-start", children: [_jsx(Link, { to: `/product/${product.id}`, className: "font-display font-bold text-lg text-primary-green hover:text-accent-orange transition-colors", children: product.name }), _jsxs("span", { className: "font-bold text-primary-green", children: ["$", product.price.toFixed(2)] })] }), _jsx("p", { className: "text-zinc-500 text-sm line-clamp-1", children: product.description }), _jsxs("div", { className: "flex items-center space-x-2 pt-2", children: [_jsxs("span", { className: "text-[10px] font-bold bg-soft-cream text-primary-green px-2 py-0.5 rounded uppercase", children: [product.age_group, " yrs"] }), _jsx("span", { className: "text-[10px] font-bold bg-soft-cream text-primary-green px-2 py-0.5 rounded uppercase", children: product.gender })] })] })] }));
}
//# sourceMappingURL=ProductCard.js.map